### PR TITLE
Remove deprecated `next` param

### PR DESCRIPTION
**Pull request by alexbestul**

### CODE REVIEW

**Comment by ebuzyuma** [comment]
The change is good. 
But just a few minor fixes needed: 

- [ ] Update package version in package.json (to 1.0.3)
- [ ] execute `npm run build` to have dist files updated

**Review by ebuzyuma — CHANGES_REQUESTED** [review]
Looks good. 
But just a few minor fixes are needed: 

- [x] Update package version in package.json (to 1.0.3)
- [x] execute `npm run build` to have dist files updated

**Comment by alexbestul** [comment]
Package version and dist files are updated now.

**Review by ebuzyuma — APPROVED** [review]
LGTM!

**Pull request merged**
